apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jellyfin
  labels:
    name: jellyfin
spec:
  tls:
    - hosts:
        - jellyfin.internal.vkolobara.com
  rules:
    - host: jellyfin.internal.vkolobara.com
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: jellyfin
                port:
                  number: 8096
