apiVersion: v1
kind: Service
metadata:
  name: jellyfin
spec:
  selector:
    app: jellyfin
  ports:
    - port: 8096
      targetPort: 8096
---
apiVersion: v1
kind: Service
metadata:
  name: jellyfin-lb
spec:
  selector:
    app: jellyfin-lb
  ports:
    - port: 8096
      targetPort: 8096
  type: LoadBalancer
