apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: huginn
spec:
  chart:
    spec:
      chart: huginn
      sourceRef:
        kind: HelmRepository
        name: huginn
      version: 2.1.1
  interval: 1m0s
