apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tdarr-config
spec:
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: tdarr-data
spec:
  capacity:
    storage: 100Gi
  volumeMode: Filesystem
  type: csi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: smb-media
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tdarr-data
spec:
  resources:
    requests:
      storage: 1Gi
  volumeName: tdarr-data
  accessModes:
    - ReadWriteOnce
