apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - secret-sealed.yaml
  - serviceaccount.yaml
  - clusterrole.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
