apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jellyseerr
  labels:
    name: jellyseerr
spec:
  rules:
    - host: jellyseerr.vkolobara.home
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: jellyseerr
                port:
                  number: 5055
