apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: pihole
spec:
  chart:
    spec:
      chart: pihole
      sourceRef:
        kind: HelmRepository
        name: pihole
      version: 2.29.1
  values:
    serviceDns:
      loadBalancerIP: "192.168.0.201"
      loadBalancerIPv6: "192.168.0.201"
      type: "LoadBalancer"
      mixedService: true
    serviceDhcp:
      enabled: true
      loadBalancerIP: "192.168.0.201"
      loadBalancerIPv6: "192.168.0.201"
      type: "LoadBalancer"
    serviceWeb:
      loadBalancerIP: "192.168.0.201"
      loadBalancerIPv6: "192.168.0.201"
      type: "LoadBalancer"
      https:
        enabled: true
        nodePort: 8443
      http:
        enabled: false
        nodePort: 8080
    persistentVolumeClaim:
      enabled: true
      storageClass: smb-data
      accessModes:
        - ReadWriteMany
    doh:
      enabled: true
    adlists:
      - https://big.oisd.nl
    podDnsConfig:
      enabled: true
      policy: "None"
      nameservers:
        - 127.0.0.1
        - 1.1.1.1
        - 1.0.0.1
  interval: 1m0s
