apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: pihole
spec:
  chart:
    spec:
      chart: pihole
      sourceRef:
        kind: HelmRepository
        name: pihole
      version: 2.22.0
  values:
    serviceDns:
      loadBalancerIP: "192.168.0.200"
      loadBalancerIPv6: "192.168.0.200"
      type: "LoadBalancer"
    serviceDhcp:
      loadBalancerIP: "192.168.0.200"
      loadBalancerIPv6: "192.168.0.200"
      type: "LoadBalancer"
    serviceWeb:
      loadBalancerIP: "192.168.0.200"
      type: "LoadBalancer"
    persistentVolumeClaim:
      enabled: true
      storageClass: smb-data
    doh:
      enabled: true
    podDnsConfig:
      enabled: true
      policy: "None"
      nameservers:
        - 127.0.0.1
        - 8.8.8.8
  interval: 1m0s
