apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: fantazista
  namespace: fantazista
spec:
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: fantazista
  path: ./
  prune: true
