apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: fantazista
spec:
  interval: 1m0s
  url: ssh://git@github.com/fantazista/ops
  ref:
    branch: main
  secretRef:
    name: git-auth