apiVersion: apps/v1
kind: Deployment
metadata:
  name: paperless
spec:
  selector:
    matchLabels:
      app: paperless
  template:
    metadata:
      labels:
        app: paperless
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - pc
      containers:
        - name: paperless
          image: ghcr.io/paperless-ngx/paperless-ngx:latest
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: Europe/Zagreb
            - name: PAPERLESS_DBENGINE
              value: mariadb
            - name: PAPERLESS_DBHOST
              value: mariadb
            - name: PAPERLESS_DBUSER
              value: paperless
            - name: PAPERLESS_DBPASS
              value: paperless
            - name: PAPERLESS_DBPORT
              value: "3306"
            - name: PAPERLESS_REDIS
              value: "redis://redis:6379"
            - name: PAPERLESS_URL
              value: "https://paperless.internal.vkolobara.com"
            - name: PORT
              value: "8000"
          ports:
            - containerPort: 8000
          volumeMounts:
            - mountPath: /usr/src/paperless/data
              name: data
            - mountPath: /usr/src/paperless/media
              name: media
            - mountPath: /usr/src/paperless/export
              name: export
            - mountPath: /usr/src/paperless/consume
              name: consume
      volumes:
        - name: consume
          nfs:
            path: /mnt/disk1/paperless-ngx/paperless/consume
            server: 192.168.0.14
        - name: export
          nfs:
            path: /mnt/disk1/paperless-ngx/paperless/export
            server: 192.168.0.14
        - name: data
          nfs:
            path: /mnt/disk1/paperless-ngx/paperless/data
            server: 192.168.0.14
        - name: media
          nfs:
            path: /mnt/disk1/paperless-ngx/paperless/media
            server: 192.168.0.14
