apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: k8s-gateway
  namespace: k8s-gateway
spec:
  chart:
    spec:
      chart: k8s-gateway
      sourceRef:
        kind: HelmRepository
        name: k8s-gateway
      version: 2.0.0
  values:
    domain: "vkolobara.home"
    watchedResources: ["Ingress"]
    service:
      loadBalancerIP: "192.168.0.200"
  interval: 1m0s
