apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: smb-csi
spec:
  interval: 1m0s
  url: https://raw.githubusercontent.com/kubernetes-csi/csi-driver-smb/master/charts
