apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: smb-media
provisioner: smb.csi.k8s.io
parameters:
  source: "//192.168.0.14/media"
  csi.storage.k8s.io/provisioner-secret-name: "smbcreds"
  csi.storage.k8s.io/provisioner-secret-namespace: "smb-csi"
  csi.storage.k8s.io/node-stage-secret-name: "smbcreds"
  csi.storage.k8s.io/node-stage-secret-namespace: "smb-csi"
  subDir: "/"
reclaimPolicy: Retain
volumeBindingMode: Immediate
mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - uid=1001
  - gid=1001
  - noperm
  - mfsymlinks
  - cache=strict
  - noserverino
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: smb-torrent
provisioner: smb.csi.k8s.io
parameters:
  source: "//192.168.0.14/torrent"
  csi.storage.k8s.io/provisioner-secret-name: "smbcreds"
  csi.storage.k8s.io/provisioner-secret-namespace: "smb-csi"
  csi.storage.k8s.io/node-stage-secret-name: "smbcreds"
  csi.storage.k8s.io/node-stage-secret-namespace: "smb-csi"
  subDir: "/"
reclaimPolicy: Retain
volumeBindingMode: Immediate
mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - uid=1001
  - gid=1001
  - noperm
  - mfsymlinks
  - cache=strict
  - noserverino