apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: paperless

resources:
  - namespace.yaml
  - redis.yaml
  - postgres-secret-sealed.yaml
  - postgres.yaml
  - deployment.yaml
  - service.yaml
