---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: postgres
spec:
  encryptedData:
    POSTGRES_DB: AgCEBll4dgxV3/btdbyUNOSZ3yiugQnlKuKI1mjZw5yZ4zROIPoxKJ/cHLqJG/Y0d/9zKGRDcU8ssWl4mookeiFTyt37dctX/YnTly3tk0nXKQndefkx8BWMfb04guaVRXM0PE4R3Jn6iskQOPe7FxGLF1EaOOUHlH5lkzAPGjWPvMq0uL1Ts5IPPs3h3PdE1r1l0TmlXux9V5e0Uw4jnV4w3DGDGAuwd/HN8GkdS4A/w09n7EUj4gOLy1snGCaui2VZrk9DM2B8tnpwfAJD1hre2Qm7bF3kLEoXGgPaNBDdxT7hos8DkuV3Xsl2dwhmPde8ss1YavPdQMOF5xRCUMuGDF/XF3zIucuTnwq2koEgrBD30sEm8LSdOJhK8qjxP9h3SCvuEAYVxK6TMxhOqNchTvlZitK8ni/+1k3Nsqo9sx95vtuzKmvBRQDFHtoi+nsWMhd61YAP1avMdqtIL3qLhxBMEi7jZnvw+9Nn29DQl1cGLESRYtnFzJ/dARuTReL2pwm2TKgumPNdxfFUuXbqpU4UExRvJICTAnIOw9JeWTeocQeKNs09xLhjieO8xMuhIk5C5miPbv8oMMUtDpa35OZAYhMS8LIarj8zH0OMEqUHLBtNHuxvsYNJoJlAfgo2nC4HQbAvBfU2DZQb2ruex5gMSp6CELXa4vlske0xs48WRZAv9Nl12/qLnrjewYM8TCWqkppu8og=
    POSTGRES_PASSWORD: AgCxSI2XVn83m44LJQNd87FaasZvc0H6TiD0JX9CIKK8mfLpv0QAjwir22tjNeBflFAfGoQ6HMcv3jERzoy7vrpB+JETuGi8aC+L3nYXT8cwFx4IFP/lR4zmC2v3UowxttCIjM/N/ayTahMHTre6FiTD9k15UCNKev+U5NdHqSJ3SnDFIqXgpmLLTrQdbwff44CQfJelEWHTaszfkK03BtB9ZgxdBye0jHqGL9Cvbi1j8pL/YbAnocUbKxq5P4840cyZLgLAcejAMei+jl/Rr9RWL7UjESbceu0pFmd5mhlu48TjHl4gfaSfQbWoOynHwiCIMs+ZFgQLX6botSQxe4EGKgjEKnJprK1lAuehLW1GO/muPy+59ZRoN5S3jjnwelszqXWEqKhruFDFLJkqqKXkL3Wkru6d8TKTXd+CFwImyTCO6vD8N4h1veSZvNS8m/qEhh5sfvppt01aQuwlY20vL1r0pMlbIuvIyL1804CASiMJGjfChLcD5ODPr3GT8xrayBwDe+ij4iX+zbF4GonTXgT2sRoIuLcXvmTCkihWvcZt5sDN0O5xwZtA9xnDwdtWQ59+g6y4O9s0cdMpeazJjdisliZsNHSFx6MjWTrpZRbC9xNRoYGRQ3FlrRCAWuE5qZMN5pPpyGs+Ws/p42bKVxG35gQQnglV1UJcHdR1wAcz1iCOzladMEmoGzq5XPPX5WPDD/77jsY=
    POSTGRES_USER: AgCi94ruTBklY/HuQffvA8YW25rlOJfxg7DddTxUeemHwCzsaZkn7stlupHr3cGZ42Vj8p2bkSg97XnCtMBGTWwyADdnV3yrt/6y/dgXKhVIzJpkbClaQol+pQ/ghozN+KvY6pucMLWM6oSInx50fqeEQ6dsG3UO8lGXGQSvOHaLGeCx9LZ6HrBZgsL5wbrOIZTejB+FLUbv+wwhCHaWParf4JQkwRQKUwSpo9S6JIAQu1ZVAFDTSaDpFxVwsnWbi9+uOLBrWBSXTki98m3fDGGO1q9PkCjtxmkhs+HgWoRmiWbgGFsV/gP1WbOWXNrLkAJOh9MafXZsUooIcwHKavAiRlthrrfxzwDjHoYbF03wmQ9ZbcUyqH+0zDDKCt6RwHlTAWk0N9pJhhiQVRGDFk/ati2kzbg9Sxf5GX8sadSqSwbHQVIfB4HTqRfnNASGBvUgPSoYXteB6MB7B3GBabDBbiLzQX6wABL6x5NmnGb8Uwm7cwlq4GoJ4jp/a4vTXypH1sQKzYfJszCrFfr2UXRCfxy0k29+tiPl8VAv/BKRL8LKtG7PHwKBixhXMfM4C3jfG/RA739S0QamJ1PNlMV0EPwWZKWtqKHF6xsuL8vDbfDYDeVRwYFo8ME/HwlWOHmT7YJq88QmQaECMW2/u3x9y8JzxVyae3VQMPQ7eM054356S9AxCYkQvl2emb2+640qqozuaLywiNU=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      labels:
        app: postgres
      name: postgres
