apiVersion: apps/v1
kind: Deployment
metadata:
  name: jackett
spec:
  selector:
    matchLabels:
      app: jackett
  template:
    metadata:
      labels:
        app: jackett
    spec:
      containers:
        - name: jackett
          image: lscr.io/linuxserver/jackett:latest
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: Europe/Zagreb
          ports:
            - containerPort: 9117
          resources:
            limits:
              cpu: 2000m
              memory: 2Gi
          volumeMounts:
            - mountPath: /data/torrent
              name: data
            - mountPath: /config
              name: config
      volumes:
        - name: data
          nfs:
            path: /data/torrent
            server: 192.168.0.14
        - name: config
          persistentVolumeClaim:
            claimName: jackett-config
