apiVersion: apps/v1
kind: Deployment
metadata:
  name: deluge
spec:
  selector:
    matchLabels:
      app: deluge
  template:
    metadata:
      labels:
        app: deluge
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - pc
      containers:
        - name: deluge
          image: lscr.io/linuxserver/deluge:latest
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: Europe/Zagreb
          ports:
            - containerPort: 8989
          volumeMounts:
            - mountPath: /data/torrent
              name: data
            - mountPath: /config
              name: config
      volumes:
        - name: data
          nfs:
            path: /mnt/external/torrent
            server: 192.168.0.14
        - name: config
          persistentVolumeClaim:
            claimName: deluge-config
