apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: deluge
  labels:
    name: deluge
spec:
  tls:
    - hosts:
        - deluge.internal.vkolobara.com
  rules:
    - host: deluge.internal.vkolobara.com
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: deluge
                port:
                  number: 8112
