apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: deluge-config
spec:
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:

  name: deluge-data
spec:
  resources:
    requests:
      storage: 1Gi
  storageClassName: smb-torrent
  accessModes:
    - ReadWriteOnce