apiVersion: v1
kind: PersistentVolume
metadata:
  name: registry-data
spec:
  capacity:
    storage: 64Gi
  accessModes:
  - ReadWriteMany
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Delete
  storageClassName: smb-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: registry-data
spec:
  resources:
    requests:
      storage: 64Gi
  volumeName: registry-data
  accessModes:
    - ReadWriteOnce
