---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: token
spec:
  encryptedData:
    token: AgAHQYQoH5yorw0Gic5wNBRUXdd4IVVtL9Q+9D14des86xqP86cx7Ylx1AVk0di/Uxa8KoGr4LrJr4yzkHobLAF5Sog2m9JpTNTc/udMqu75DsllLBU8XM6D5OJvMZpRqFID19UiKHlYlCJvfbLafRtZEQxP7KrYTfIcp1r1GtpBmmCrt4dt6NHqm2gdzjO432Em32NUXUgJuuBS7atEFgBeE6zzIX6G4q2dMgskoKO46fBTT7rF3VPXIP41aeSvZY2M1A7vtQXf0ZXVzAxDVHnw65UIKJIr3lSh0CypgrzldT1uoz6bdMm53qJkNMbnE8JcQt5GpWDsmOYcolw015HuDTIG8igUPNAIg5JKF+V6+fZ9i5HBfoYUknXB6H0TEj0VLE69SRAI5nU38g9uYGIYtsFuNm7vSmd5OhM8x/CxWakp7ELREIa/c3X2AWuWjBbKFlWWAlt+8BJspu47GPakfVgoRenkBlpdrBIbY5fB1g6hwMpz0lVrVI905hHGlQ6HWKLLDgWFAJA/yLSXB0zuVSwpVBddXjgaXrqmZsFBdZsu1NVu1QXHpeMPygxHNK2xEVsOS0SHaQdMbxpFui6EfvqDgxyvAqihQjzK18vABGHYmietNr94fUYdwdkAntoTuyj/ERTy2R2h8KThoUpbFLEm4FZxrZG8XhCDafzZHzyCLl9m33DTxCKRH5JfJD4TGZWpU+Pl/Vrc22JoDvSL/FXLtUn6LaAEVIf8ahAD8FPXyFIquujGLuiZNbei7pk8kDJeEt5w5pgTuST9eXF4ci7ZULTQkpqRh78vwU8HK1ZuLXQgO+Z8oYpYrwr1k1Cw3cGAuWhKHX1BqhbLzjabqSl8w0qXpRVms9xX/yi4feeRCwQ2+sCnJauXi2GI2nTN/DBXUbvkngpJOSgqKWm64YIVPI3GHYBMqH+PrSfEuIxTFlr4yaXJ
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: token
