---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: pihole-password
spec:
  encryptedData:
    EXTERNAL_DNS_PIHOLE_PASSWORD: AgAdpbEYvk4xJxhuXd0CdqabNs/YtCXgILFM+INrN1sK4XV9w6hJTRxuvBbjY/ZY2HTtmV8dPDh1AR+bTfR1Eskt1W2bPBDT1Gq/Z/AiD8LHTIfk5iPQwYFxjAKE1+V9u+3UA9Ks+HbRNTbaA+YqYKsHkdCnkssdHhcF3u6GaqeLt0IU2YVdodHbyqKtyWy0KThgiywHzwYS0vsedqKbDJYrOAfa2hRey/kGxIY8N5pLk1lfHdmFdAs5/dTMZ6EZXlK0yYSrb4O5X1k/zUtduNxBcq4WzHThz7jhXYLEhfLcTdbe0BX8ZSjdaKQxQy792wHHxwXdK55Ke1KIJA3E8n7TUw3I6jvmWHGXeZvJ0DR0zqagFs5fszhGggP/eVE8UBQ70VYnRc+NmZVqVUB6mbXQKEjLz+I5a8bdahr+9U/7PYLImc6v2GSgqFmCI23rLKBeqqA0nyL6beyM4Ltk6yhl7daV6WjqlwgdNGrHeieRwTX/2eup42UQKn5DyYNRRObPQyDSt1Miv9N5dolzQqrbWFQi4TZkaxwOIStYR8higj3vBk7Cqkg8MrFnqReoY5CL3zMKO3rMmzCwqQ6f7FSa8D/WMCH8tJO94n3oxb2yaYXML3o6+VcAAPrTjAadmZvcvTeUIxXEP710rHb787KRkgZRshxI2S7gCaDl0cfwBjJfQSSNvCAwN7UOiofR46M+3Uo1HA==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: pihole-password
