apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs-server
  namespace: nfs
spec:
  selector:
    matchLabels:
      app: nfs-server
  template:
    metadata:
      labels:
        app: nfs-server
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - pc
      containers:
        - name: nfs-server
          image: erichough/nfs-server:2.2.1
          ports:
            - containerPort: 2049
            - containerPort: 111
            - containerPort: 32765
            - containerPort: 23767
          securityContext:
            privileged: true
          volumeMounts:
            - name: data
              mountPath: /data
          env:
            - name: NFS_EXPORT_0
              value: "/data *(rw,no_subtree_check)"
      volumes:
        - name: data
          hostPath:
            path: /mnt/external
