apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: k8s-gateway
spec:
  chart:
    spec:
      chart: k8s-gateway
      sourceRef:
        kind: HelmRepository
        name: k8s-gateway
      version: 1.1.9
  values:
    domain: "internal.vkolobara.com"
    watchedResources: ["Ingress"]
    service:
      loadBalancerIP: "192.168.0.200"
    extraZonePlugins: "forward . 1.1.1.1 1.0.0.1"
  interval: 1m0s
