apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bazarr
  labels:
    name: bazarr
spec:
  rules:
    - host: bazarr.vkolobara.home
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: bazarr
                port:
                  number: 8989
