---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: cloudflare-api-token
spec:
  encryptedData:
    token: AgCH46MxzppuytXrKKsc2TLbML3SEmHl9ywK4yjU1pmSRzYZ2NYFnuD9Cx/7Y+itSQh8eCNx1cQPAqfa6+dwZjMHO7dGmVMGlW6N12Gyd7CHqAafmpXYIlhJyYe6xbCLIP3WOPb3Pu9RyrbYPMIXvCfcKrEmFNepnRiKDlh0OFeLkyFSHuVJKKsJfLJ3Kv/PiptXKS+iMrIRT6G27ZXf6WtflJ7abgTX2mJ0nNPIfEpruxLOCRl8msFkZ3G9X4x9Jw/RFAnTwB3D5yAJo3MxYx3nf5vCMzaARqvqlxPzCPBAR/XTa/AZRZpAF0/qhWcvleWnCw1dvbGrqtNRz1PdYf/Ppz6p4M/hXD3bxFmOGrBq9f6HOGKx7xIi04vmY9lPWnOXo8osoXX8D2jxoL0Ztdom8b6yY+FTxe6Z/OfKQskrulNoAWLAlCdbFQBHliMRcUF+4N+J13etpr8B+ENntMp0yZbB3zYYrlqkQ44k4Iyg9D/9dn+D900IoUn8Oddb+xqv1BHQpqDwPN2KVP4FzIZK90HacSXuTdLmW1YFSEzdf2QjwtyreKeaO+bNKbFsMSh3zERDhnrLVf2W6La4aGizgPezOLF/X1VmSv5sbwQ69XFBWyZgsNvARzIRZwB55rMV+JEghKNboW8ah5gBqRskisRSRzUeK8G1/8pJjXoTB+f9mVlVnqPlSvO4pz8d2Vy7TjJpCUjs3Qa8jyOJoT5A8dqGuwFAE7phUAxdXCy05NCd43q2GUN6
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: cloudflare-api-token
    type: Opaque
