apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: k8s-gateway
  annotations:
    fluxcd.io/automated: "false"
    fluxcd.io/tag.chart-image: semver:~4.0
spec:
  releaseName: k8s-gateway
  chart:
    repository: https://ori-edge.github.io/k8s_gateway/
    name: k8s-gateway
    version: 2.0.0
  values:
    domain: "vkolobara.home"
    service:
      externalIPs:
        - "192.168.0.200"
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: kubernetes.io/hostname
                  operator: In
                  values:
                    - rpi-1
