apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mylar-config
spec:
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mylar-data
spec:
  capacity:
    storage: 100Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-path
  local:
    path: /mnt/disk1
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - pc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mylar-data
spec:
  resources:
    requests:
      storage: 1Gi
  volumeName: mylar-data
  accessModes:
    - ReadWriteOnce
